services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - LITELLM_MASTER_KEY=sk-1234
      - GEMINI_API_KEY=SAIzaSyAO4iKeVfNqMNnjDYiiK6Vl9RitjRdYhLw
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--detailed_debug" ]